# Generated by Django 4.1.4 on 2022-12-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Suallar'},
        ),
    ]
