# Generated by Django 4.1.4 on 2023-01-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('kişi', 'Kişi'), ('qadın', 'Qadın')], max_length=50, null=True)),
                ('day', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=10, null=True)),
                ('month', models.CharField(blank=True, choices=[('yanvar', 'Yanvar'), ('fevral', 'Fevral'), ('mart', 'Mart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'İyun'), ('iyul', 'İyul'), ('avqust', 'Avqust'), ('sentyabr', 'Sentyabr'), ('oktyabr', 'Oktyabr'), ('noyabr', 'Noyabr'), ('dekabr', 'Dekabr')], max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('telephon', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('district', models.CharField(choices=[('bakı', 'Bakı'), ('gəncə', 'Gəncə')], max_length=50)),
                ('id_card_seria', models.CharField(choices=[('aze', 'AZE'), ('aa', 'AA'), ('myi', 'MYİ'), ('dyi', 'DYİ')], default='AZE', max_length=20)),
                ('fin_code', models.CharField(max_length=7, null=True, unique=True)),
                ('id_card_number', models.CharField(max_length=7, null=True, unique=True)),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
                ('filial', models.CharField(max_length=50)),
                ('password_again', models.CharField(blank=True, max_length=8, null=True)),
                ('promocode', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
                ('adress2', models.CharField(blank=True, max_length=50, null=True)),
                ('quarter', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=10)),
                ('detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.countrydetail')),
            ],
        ),
    ]
