# Generated by Django 4.1.4 on 2023-01-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='month',
            field=models.CharField(blank=True, choices=[('yanvar', 'Yanvar'), ('fevral', 'Fevral'), ('mart', 'Mart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'İyun'), ('iyul', 'İyul'), ('avqust', 'Avqust'), ('sentyabr', 'Sentyabr'), ('oktyabr', 'Oktyabr'), ('noyabr', 'Noyabr'), ('dekabr', 'Dekabr')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
