# Generated by Django 4.1.4 on 2022-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='promocode',
            field=models.IntegerField(null=True),
        ),
    ]
