# Generated by Django 4.1.4 on 2023-01-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_month_alter_customuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='promocode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
