# Generated by Django 4.1.4 on 2023-01-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='month',
            field=models.CharField(choices=[('yanvar', 'Yanvar'), ('fevral', 'Fevral'), ('mart', 'Fart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'İyun'), ('iyul', 'İyul'), ('avqust', 'Avqust'), ('sentyabr', 'Sentyabr'), ('oktyabr', 'Oktyabr'), ('noyabr', 'Noyabr'), ('dekabr', 'Dekabr')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2004),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(choices=[('bakı', 'Bakı'), ('gəncə', 'Gəncə')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('kişi', 'Kişi'), ('qadın', 'Qadın')], max_length=50, null=True),
        ),
    ]
