# Generated by Django 4.1.4 on 2023-01-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_day_customuser_id_card_customuser_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_card',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
