# Generated by Django 4.1.4 on 2022-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('heigth', models.FloatField()),
                ('country', models.CharField(choices=[('çin', 'ÇİN'), ('abş', 'ABŞ'), ('türkiyə', 'TÜRKİYƏ')], default='TÜRKİYƏ', max_length=50)),
                ('shipping', models.CharField(choices=[('çin', 'ÇİN'), ('abş', 'ABŞ'), ('türkiyə', 'TÜRKİYƏ')], default='Adresə çatdırılma', max_length=50)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
