# Generated by Django 4.1.4 on 2022-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_sizeproduct_heigth_remove_sizeproduct_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
