# Generated by Django 4.1.4 on 2022-12-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_calculateshipping_input_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculateshipping',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
