# Generated by Django 4.1.4 on 2022-12-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_calculateshipping_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculateShipping',
        ),
    ]
