# Generated by Django 4.1.4 on 2023-01-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_orders_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_link',
            field=models.URLField(default='url'),
        ),
    ]
