# Generated by Django 4.1.4 on 2023-01-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='product_link',
        ),
    ]
