# Generated by Django 4.1.4 on 2023-01-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_profile_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='increasebalance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance', to='dashboard.profile'),
        ),
    ]
