# Generated by Django 4.1.4 on 2023-01-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_increasebalance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.increasebalance'),
        ),
    ]
