# Generated by Django 4.1.4 on 2023-01-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_order_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increasebalance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_balance', to='dashboard.profile'),
        ),
    ]
