# Generated by Django 4.1.4 on 2022-12-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_remove_methods_countryandmethod_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Methods',
            new_name='RateType',
        ),
        migrations.RenameField(
            model_name='tarif',
            old_name='countryandmethod',
            new_name='countryandtype',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='first_weight',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='last_weight',
        ),
        migrations.AddField(
            model_name='tarif',
            name='rangeweight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
