# Generated by Django 4.1.4 on 2022-12-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_rename_methods_ratetype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Ölkələr'},
        ),
        migrations.AlterModelOptions(
            name='ratetype',
            options={'verbose_name_plural': 'Tariflərin Növü'},
        ),
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name_plural': 'Tariflər'},
        ),
        migrations.AlterField(
            model_name='country',
            name='cargo_type',
            field=models.ManyToManyField(blank=True, to='rates.ratetype'),
        ),
    ]
