# Generated by Django 4.1.4 on 2022-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_link', models.URLField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/shop_photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Mağazalar',
            },
        ),
    ]
