# Generated by Django 4.1.4 on 2022-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_country_shop_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Ölkələr'},
        ),
    ]
