# Generated by Django 4.1.4 on 2022-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
